# render.yaml
services:
  - type: web
    name: centauro-scraper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # Usa Gunicorn para rodar o app Flask
    plan: free # Define o plano gratuito
    # Para evitar que o serviço caia em inatividade, defina um health check
    healthCheckPath: /
    autoDeploy: true # Ativa o deploy automático a cada push no GitHub
